language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.0
script:
- set -o pipefail
- xcodebuild -project CHPermissions.xcodeproj -scheme "CHPermissions" -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
