name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project CHPermissions.xcodeproj -scheme "CHPermissions" -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
